# Generated by Django 5.1.6 on 2025-02-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
