# Generated by Django 5.1.6 on 2025-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hisse2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=10, unique=True)),
                ('fiyat', models.FloatField()),
                ('fiyat_degisim_yuzdesi', models.FloatField(default=0.0)),
                ('hacim', models.BigIntegerField()),
                ('zaman', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
