# Generated by Django 5.1.6 on 2025-03-05 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0002_hisse2'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisse2',
            name='kategori',
            field=models.CharField(choices=[('XU30', 'BIST 30'), ('XU100', 'BIST 100'), ('BISTTUM', 'Tüm Hisseler')], default='BISTTUM', max_length=10),
        ),
        migrations.CreateModel(
            name='StockAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField()),
                ('is_above', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borsa.hisse2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserStockTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('hisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borsa.hisse2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'hisse')},
            },
        ),
    ]
