# Generated by Django 5.1.6 on 2025-03-05 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0003_hisse2_kategori_stockalarm_userstocktracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hisse2',
            name='kategori',
        ),
        migrations.AddField(
            model_name='hisse2',
            name='is_bisttum',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hisse2',
            name='is_xu100',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hisse2',
            name='is_xu30',
            field=models.BooleanField(default=False),
        ),
    ]
