# Generated by Django 5.1.6 on 2025-03-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0004_remove_hisse2_kategori_hisse2_is_bisttum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisse2',
            name='exchange',
            field=models.CharField(default='BIST', max_length=20),
        ),
    ]
