# Generated by Django 5.1.6 on 2025-03-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0007_stockdata_alter_analysis_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockData',
        ),
    ]
