# Generated by Django 5.1.6 on 2025-03-01 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0002_comment_like_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saved',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Saved',
        ),
    ]
