# Generated by Django 5.1.6 on 2025-03-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0007_customuser_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_premium',
        ),
    ]
