# Generated by Django 5.1.6 on 2025-03-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borsa', '0009_customuser_is_premium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
